import numpy as np
import plotly.graph_objects as go
from coms import *

# Generated by SuperMan.export_py
nodes_params = {}
nodes_params['awg'] = {'mode': 'seq', 'sampling_rate': 50000000000000.0, 'per': 1e-10, 'sequence': [1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0], 'pulse_shape': 'rec', 'gauss_sigma_frac': 0.18, 'low': 0.0, 'high': 1.0}
nodes_params['lpf7'] = {'R': 50, 'C': 4.55e-13}
nodes_params['ng'] = {'noise_std': 2, 'mean': 0.0, 'seed': 42}
nodes_params['lpf1'] = {'R': 50, 'C': 4.5e-14}
nodes_params['osc'] = {'width': 900, 'height': 450, 'plot_modes': {'time1': 'time', 'time2': 'time', 'time3': 'time', 'time4': 'time', 'time5': 'time', 'time6': 'time', 'eye1': 'eye', 'eye2': 'eye', 'eye3': 'eye', 'eye4': 'eye', 'eye5': 'eye', 'eye6': 'eye', 'custom1': 'auto', 'custom2': 'auto', 'custom3': 'auto', 'custom4': 'auto'}, 'plot_titles': {'time1': 'AWG (Clean)', 'time2': 'After Noise Generator', 'time3': 'After LowPassFilter', 'eye1': 'Eye Diagram @ 7GHz LPF', 'eye2': 'Eye Diagram @ Final LPF', 'custom1': 'Photodetector Output'}, 'eye_slot_duration': 1e-10, 'eye_bit_rate': None, 'eye_slots': 3, 'eye_max_traces': 80}

awg = ArbitraryWaveformGenerator(mode='seq', sampling_rate=50000000000000.0, per=1e-10, sequence=[1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0], pulse_shape='rec', gauss_sigma_frac=0.18, low=0.0, high=1.0)
lpf7 = LowPassFilter(R=50, C=4.55e-13)
ng = ElectricalNoiseGenerator(noise_std=2, mean=0.0, seed=42)
lpf1 = LowPassFilter(R=50, C=4.5e-14)
osc = Oscilloscope(width=900, height=450, plot_modes={'time1': 'time', 'time2': 'time', 'time3': 'time', 'time4': 'time', 'time5': 'time', 'time6': 'time', 'eye1': 'eye', 'eye2': 'eye', 'eye3': 'eye', 'eye4': 'eye', 'eye5': 'eye', 'eye6': 'eye', 'custom1': 'auto', 'custom2': 'auto', 'custom3': 'auto', 'custom4': 'auto'}, plot_titles={'time1': 'AWG (Clean)', 'time2': 'After Noise Generator', 'time3': 'After LowPassFilter', 'eye1': 'Eye Diagram @ 7GHz LPF', 'eye2': 'Eye Diagram @ Final LPF', 'custom1': 'Photodetector Output'}, eye_slot_duration=1e-10, eye_bit_rate=None, eye_slots=3, eye_max_traces=80)

edges = [
    ('awg', 'el_out', 'lpf7', 'el_in'),
    ('lpf7', 'el_out', 'ng', 'el_in'),
    ('ng', 'el_out', 'lpf1', 'el_in'),
    ('awg', 'el_out', 'osc', 'time1'),
    ('ng', 'el_out', 'osc', 'time2'),
    ('lpf1', 'el_out', 'osc', 'time3'),
    ('lpf7', 'el_out', 'osc', 'eye1'),
    ('lpf1', 'el_out', 'osc', 'eye2'),
]
order = ['awg', 'lpf7', 'ng', 'lpf1', 'osc']

instances = {
    'awg': awg,
    'lpf7': lpf7,
    'ng': ng,
    'lpf1': lpf1,
    'osc': osc,
}
outputs = {}

def _first(values, typ):
    for v in values:
        if isinstance(v, typ):
            return v
    return None

def incoming(node):
    inc = {}
    for s, sp, d, dp in edges:
        if d != node:
            continue
        sig = outputs.get(s, {}).get(sp)
        if sig is None:
            continue
        inc.setdefault(dp, []).append(sig)
    return inc

def normalize(nid, value):
    if isinstance(value, dict):
        return value
    out = {
        'awg': 'el_out',
        'lpf7': 'el_out',
        'ng': 'el_out',
        'lpf1': 'el_out',
        'osc': None,
    }
    p = out.get(nid)
    return {} if p is None else {p: value}

for nid in order:
    inst = instances[nid]
    inc = incoming(nid)
    tname = type(inst).__name__
    if tname == 'ArbitraryWaveformGenerator':
        raw = inst.generate()
    elif tname == 'Laser':
        ref = None
        for arr in inc.values():
            ref = _first(arr, ElectricalSignal)
            if ref is not None: break
        t = ref.t if ref is not None else np.arange(0, 20e-12, 1e-14)
        raw = inst.generate(t)
    elif tname == 'IntensityModulator':
        opt = _first(inc.get('opt_in', []), OpticalSignal)
        dr = _first(inc.get('el_in', []), ElectricalSignal)
        raw = inst.apply(opt, dr)
    elif tname == 'OpticalSplitter':
        opt = _first(inc.get('opt_in', []), OpticalSignal)
        o1, o2 = inst.split(opt)
        raw = {'opt_out1': o1, 'opt_out2': o2}
    elif tname == 'Fiber':
        raw = inst.propagate(_first(inc.get('opt_in', []), OpticalSignal))
    elif tname == 'Photodetector':
        raw = inst.detect(_first(inc.get('opt_in', []), OpticalSignal))
    elif tname in ('BandPassFilter','LowPassFilter','ElectricalNoiseGenerator'):
        raw = inst.apply(_first(inc.get('el_in', []), ElectricalSignal))
    elif tname in ('IncoherentDetector','CoherentDetector'):
        raw = inst.detect(_first(inc.get('opt_in', []), OpticalSignal))
    elif tname == 'Oscilloscope':
        prm = nodes_params[nid]
        modes = prm.get('plot_modes', {})
        titles = prm.get('plot_titles', {})
        for p in ['time1','time2','time3','time4','time5','time6','eye1','eye2','eye3','eye4','eye5','eye6','custom1','custom2','custom3','custom4']:
            vals = inc.get(p, [])
            sig = vals[0] if vals else None
            if sig is None: continue
            md = str(modes.get(p, 'auto')).lower()
            tt = str(p)
            if md in ('auto','time') and isinstance(sig, ElectricalSignal):
                sig.plot(title=tt)
            elif md == 'eye' and isinstance(sig, ElectricalSignal):
                inst.plot_eye(sig, title=tt, slot_duration=prm.get('eye_slot_duration'), bit_rate=prm.get('eye_bit_rate'), slots=int(prm.get('eye_slots',3)), max_traces=int(prm.get('eye_max_traces',250)))
            elif isinstance(sig, DetectorSignal):
                inst.plot_iq(sig, title=tt)
            elif isinstance(sig, OpticalSignal):
                ElectricalSignal(sig.t, np.abs(sig.A)**2).plot(title=tt)
        raw = {}
    else:
        raise RuntimeError(f'Unsupported node type {tname}')
    outputs[nid] = normalize(nid, raw)

print('Run completed. Nodes:', ', '.join(order))
